### ISSUE TITLE
ACCESS_TOKEN_RESOURCE_OWNER_ID is used incorrectly

### ISSUE THREAD

**Issue by shadowhand** [florentsorel/oauth2-betaseries#1]
The constant `ACCESS_TOKEN_RESOURCE_OWNER_ID` is meant to refer to the value in the token response that identifies the user. It should not identify the token value.

**Comment by florentsorel** [comment]
Hi,

Can you be more specific on that constant please ?

**Comment by shadowhand** [comment]
For instance, in the [Google Provider](https://github.com/thephpleague/oauth2-google/blob/1fb1f25661b5181d56b91a78525e19be5d4f3432/src/Provider/Google.php#L14) the constant is used to identify the value in the response that identifies the user that was just logged in and relates to the token. It is not the same as the token value, which is defined by the spec.

**Comment by florentsorel** [comment]
But if I provide another string as value in that constant the response is:

```
InvalidArgumentException in AccessToken.php line 58:
Required option not passed: "access_token"

at AccessToken->__construct(array('user' => array('id' => 'mybetaseriesID', 'login' => 'R-transat', 'in_account' => false), 'token' => 'myBetaseriesToken', 'hash' => null, 'errors' => array(), 'access_token' => null)) in AbstractProvider.php line 731
```

We can see the access_token is null

What's wrong in my implementation ?

**Comment by shadowhand** [comment]
Based on the values in that error, your `ACCESS_TOKEN_RESOURCE_OWNER_ID` should be `user.id` and you should be overloading the [`prepareAccessTokenResponse`](https://github.com/thephpleague/oauth2-client/blob/cea255753d9ce486c425d8126fd0e469496d25db/src/Provider/AbstractProvider.php#L708-L717) method to set `access_token` to `token`.
